#!/bin/sh

# Set these paths appropriately

BIN=/home/zagic/multiproj/tools/treetagger/bin
CMD=/home/zagic/multiproj/tools/treetagger/cmd
LIB=/home/zagic/multiproj/tools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/french-abbreviations-utf8
PARFILE=${LIB}/french-utf8.par

$TOKENIZER -f -a $ABBR_LIST $* |
$TAGGER $OPTIONS $PARFILE
