#!/bin/sh

# Set these paths appropriately

BIN=/home/zagic/multiproj/tools/treetagger/bin
CMD=/home/zagic/multiproj/tools/treetagger/cmd
LIB=/home/zagic/multiproj/tools/treetagger/lib

OPTIONS="-token -lemma -sgml"

TOKENIZER=${CMD}/utf8-tokenize.perl
MWL=${CMD}/mwl-lookup.perl
TAGGER=${BIN}/tree-tagger
ABBR_LIST=${LIB}/bulgarian-abbreviations
PARFILE=${LIB}/bulgarian-utf8.par
MWLFILE=${LIB}/bulgarian-mwls

$TOKENIZER -a $ABBR_LIST $* |
# recognition of MWLs
$MWL -f $MWLFILE |
# tagging
$TAGGER $OPTIONS $PARFILE
